resources:
  - name: java_app
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/simple-maven-sample
      branches:
        include: master

pipelines:
  - name: java_pipeline
    steps:
      - name: build_app
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          nodePool: ranjithr_pool
          integrations:
            - name: jfrogtraining
          inputResources:
            - name: java_app
          runtime:
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u16java
                tag: master
        execution:
          onComplete:
            - save_tests $res_java_app_resourcePath/target/surefire-reports/
